name: efficient-hotflip
channels:
  - soumith
  - defaults
dependencies:
  - python=3.7
  - tqdm=4.41.1
  - docopt=0.6.2
  - pip:
    - nltk==3.4.5
    - pytorch==1.4.0
    - numpy==1.18.1
    - scipy==1.3.2